###

GET http://localhost:3000/usuario

###

POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Giulia Scharman Henrique",
    "email": "giulia_haenrique@estudante.sesisenai.org.br",
    "senha_hash": "12354"
}

###

PUT http://localhost:3000/usuario/89
Content-Type: application/json

{
    "nome": "Guilherme Dalsasso Machado",
    "email": "guilherme_mAchado18@estudante.sesisenai.org.br",
    "senha_hash": "123456",
    "id": 1
}

###

DELETE http://localhost:3000/usuario/89

