### 

GET http://localhost:3000/usuario
Authorization: Bearer 

###

POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Giulia Scharman Henrique",
    "email": "giulia_haenriqaue@estudante.sesisenai.org.br",
    "senha_hash": "12354"
}

###

PUT http://localhost:3000/usuario/93
Content-Type: application/json

{
    "nome": "Guilherme Dalsasso Machado",
    "email": "guilher2e_mAchado18@estudante.sesisenai.org.br",
    "senha_hash": "123456",
    "id": 1
}

###

DELETE http://localhost:3000/usuario/93

### LOGIN

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "guilherme_machado18@estudante.sesisenai.org.br",
    "senha_hash": "12345"
}
